name: Project Deployment With Github Actions 

# on: [push, workflow_dispatch]

on:
  push: 
    branches: 
      - main
    paths-ignore: 
      - '.github/workflows/*'
      - 'README.md'
  workflow_dispatch: 

  # - workflow_dispatch

jobs:

  validate:
    runs-on: ubuntu-latest
    steps:

      - name: Code Clonning
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: '22.14.0'
      - name: Get Node Version
        run: node -v

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          Version: 10
          run_install: false
      - name: Use Cache Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.local/share/pnpm/store
          key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Project 
        run: pnpm run build 




  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonning Code
        uses: actions/checkout@v4

      - name: Setup Pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false
      - name: Install Dependencies
        run: "pnpm install --frozen-lockfile"
      - name: Build Project
        run: "pnpm run build"
      - name: "Upload Artifacts"
        uses: actions/upload-artifact@v4
        with:
          name: build-file
          path: .next
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact 
        uses: actions/download-artifact@v4
        with:
          name: build-file 
          path: .next 

      - name: "Deploy"
        run: echo "Deploying Project"




  # deploy:
  #   needs: validate
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Clonning The Code 
  #       uses: actions/checkout@v4
  #     - name: Setup Node 
  #       uses: actions/setup-node@v7
  #     - name: Setup Pnpm
  #       uses: pnpm/action-setup@v4
  #       with:
  #         version: 10
  #         run_install: false
  #     - name: Use Cache Dependencies
  #       uses: actions/cache@v4
  #       with:
  #         path: ~/.local/share/pnpm/store
  #         key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}


  #     - name: Install Dependencies
  #       run: pnpm install --frozen-lockfile
  #     - name: Build Project
  #       run: pnpm run build
  #     - name: Deploy Project 
  #       run: echo "Project Deployed Successfully"
      



#Notes := 
#1. here when we are doing caching it is only caching the pnpm store as we are dealing with pnpm so in case of caching its generally does this 
# if we truly wants to do caching like if we have already installed the dependencies dont do that again , so just simply pass the build folder from 
# validate job to deploy job and simply deploy from there else we cannot do true caching when dealing with pnpm 
